### ISSUE TITLE
neuprint_connection_table() and neuprint_simple_connectivity() return different partner sets.

### ISSUE THREAD

**Issue by AsaBarthMaron** [natverse/neuprintr#104]
I get different sets of connected partners when I query a bodyid using these two fns, but can't figure out why.
E.g.,
`neuprint_connection_table(1547454812)`
returns 647 partners
`neuprint_simple_connectivity(1547454812)`
returns 1146 partners

**Comment by romainFr** [comment]
This is because by default `neuprint_connection_table` only returns objects that have been identified as "neurons", whereas `neuprint_simple_connectivity` returns everything -- including small unidentified fragments. In `neuprint_connection_table` you'd get the same results by using the parameter `all_segments=TRUE`.

**Comment by jefferis** [comment]
```
> dim(neuprint_connection_table(1547454812,all_segments = T))
[1] 1146    4
```

**Comment by AsaBarthMaron** [comment]
Gotcha, thanks!

**Comment by jefferis** [comment]
Thanks for your interest @AsaBarthMaron. If you have any general queries about using neuprintr/natverse https://groups.google.com/forum/#!forum/nat-user is a good place to ask questions.
